# Generated by Django 2.2 on 2019-05-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('FC', 'Funcionario'), ('CL', 'Colaborador'), ('VT', 'Veterinario'), ('PT', 'Proprietario'), ('GF', 'GestorDeFazenda')], default='FC', max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('rg', models.IntegerField(max_length=11)),
                ('cpf', models.IntegerField(max_length=14)),
                ('telefone', models.IntegerField(max_length=12)),
                ('email', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('cep', models.IntegerField(max_length=8)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
    ]
